[tool.poetry]
name = "deeplearning"
version = "0.1.0"
description = ""
authors = ["Kasper MÃ¸ller Hansen <kasperhansen1998@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
